<?php

class ZenBoostPluginScaffolder
{
    public function scaffold(string $projectRoot, string $uniqueKey, string $version = 'v1.0.0', array $options = []): array
    {
        $normalizedKey = $this->normalizeKey($uniqueKey);
        if ($normalizedKey === '') {
            return [
                'ok' => false,
                'message' => 'Plugin key must contain letters or numbers.',
                'normalized_key' => $normalizedKey,
                'files' => [],
            ];
        }

        $version = trim($version);
        if ($version === '') {
            $version = 'v1.0.0';
        }

        $projectRoot = rtrim($projectRoot, '/\\') . '/';
        $pluginRoot = $projectRoot . 'zc_plugins/' . $normalizedKey . '/' . $version . '/';
        if (file_exists($pluginRoot)) {
            return [
                'ok' => false,
                'message' => 'Target plugin directory already exists.',
                'plugin_root' => $pluginRoot,
                'normalized_key' => $normalizedKey,
                'files' => [],
            ];
        }

        $displayName = trim((string)($options['name'] ?? ''));
        if ($displayName === '') {
            $displayName = $this->displayName($normalizedKey);
        }

        $author = trim((string)($options['author'] ?? ''));
        if ($author === '') {
            $author = 'Your Name';
        }

        $description = trim((string)($options['description'] ?? ''));
        if ($description === '') {
            $description = 'Encapsulated Zen Cart plugin scaffold generated by Zen Boost.';
        }

        $directories = [
            $pluginRoot . 'Installer/languages/english/',
            $pluginRoot . 'catalog/includes/classes/',
            $pluginRoot . 'catalog/includes/languages/english/',
            $pluginRoot . 'catalog/includes/modules/pages/',
            $pluginRoot . 'catalog/includes/templates/template_default/',
            $pluginRoot . 'admin/includes/classes/',
            $pluginRoot . 'admin/includes/languages/english/extra_definitions/',
            $pluginRoot . 'resources/docs-cache/',
            $pluginRoot . 'resources/catalogs/',
            $pluginRoot . 'resources/guidance/',
        ];

        foreach ($directories as $directory) {
            if (!is_dir($directory) && !mkdir($directory, 0775, true) && !is_dir($directory)) {
                return [
                    'ok' => false,
                    'message' => 'Failed to create scaffold directories.',
                    'plugin_root' => $pluginRoot,
                    'normalized_key' => $normalizedKey,
                    'files' => [],
                ];
            }
        }

        $files = [
            $pluginRoot . 'manifest.php' => $this->manifestContents($version, $displayName, $description, $author),
            $pluginRoot . 'Installer/ScriptedInstaller.php' => $this->installerContents(),
            $pluginRoot . 'Installer/languages/english/main.php' => $this->installerLanguageContents(),
            $pluginRoot . 'README.md' => $this->readmeContents($displayName, $normalizedKey, $version),
        ];

        $createdFiles = [];
        foreach ($files as $path => $contents) {
            file_put_contents($path, $contents);
            $createdFiles[] = $path;
        }

        return [
            'ok' => true,
            'message' => 'Plugin scaffold created.',
            'plugin_root' => $pluginRoot,
            'normalized_key' => $normalizedKey,
            'files' => $createdFiles,
        ];
    }

    private function normalizeKey(string $value): string
    {
        $value = strtolower(trim($value));
        $value = preg_replace('/[^a-z0-9]+/', '-', $value) ?? '';

        return trim($value, '-');
    }

    private function displayName(string $key): string
    {
        $pieces = preg_split('/[-_]+/', $key) ?: [$key];
        $pieces = array_map(static fn(string $piece): string => ucfirst($piece), $pieces);

        return implode(' ', $pieces);
    }

    private function manifestContents(string $version, string $displayName, string $description, string $author): string
    {
        return <<<PHP
<?php

return [
    'pluginVersion' => '{$this->escapePhpString($version)}',
    'pluginName' => '{$this->escapePhpString($displayName)}',
    'pluginDescription' => '{$this->escapePhpString($description)}',
    'pluginAuthor' => '{$this->escapePhpString($author)}',
    'pluginId' => 0,
    'zcVersions' => [],
    'changelog' => '',
    'github_repo' => '',
    'pluginGroups' => [],
];
PHP;
    }

    private function installerContents(): string
    {
        return <<<PHP
<?php

use Zencart\PluginSupport\ScriptedInstaller as ScriptedInstallBase;

class ScriptedInstaller extends ScriptedInstallBase
{
    protected function executeInstall()
    {
        return true;
    }

    protected function executeUninstall()
    {
        return true;
    }
}
PHP;
    }

    private function installerLanguageContents(): string
    {
        return <<<PHP
<?php

return [
];
PHP;
    }

    private function readmeContents(string $displayName, string $key, string $version): string
    {
        return <<<MD
# {$displayName}

Scaffolded by Zen Boost.

## Plugin Root

`zc_plugins/{$key}/{$version}/`

## Next Steps

- update `manifest.php` with the real plugin metadata
- add installer behavior in `Installer/ScriptedInstaller.php`
- add catalog or admin files under the encapsulated plugin directories
- install the plugin through Zen Cart Plugin Manager before testing runtime behavior
MD;
    }

    private function escapePhpString(string $value): string
    {
        return str_replace(['\\', '\''], ['\\\\', '\\\''], $value);
    }
}
